services:
  sense_app:
    container_name: sense_project
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "${FLASK_RUN_PORT}:8081"
    depends_on:
      - sense_postgres
    env_file:
      - .env
    volumes:
      - sense-app:/app/data
    networks:
      - sense-networks

  frontend:
    build: ../../Downloads/SenseFrontend
    container_name: SenseFrontend
    ports:
      - "8081:80" # Expose frontend on localhost:8081
    networks:
      - sense-networks
    environment:
      - REACT_APP_BACKEND_URL=http://localhost:${FLASK_RUN_PORT} # Use Docker service name


  sense_postgres:
    image: postgres:latest
    environment:
      POSTGRES_DB: sense_project
      POSTGRES_USER: sense_project_user
      POSTGRES_PASSWORD: sense_project_user
    volumes:
      - pgdata:/var/lib/postgresql/data
    env_file: 
      - .env
    ports:
      - "5433:5432"
    networks:
      - sense-networks

  sense_redis:
    image: redis
    deploy:
      resources:
        limits:
          memory: 2G 
    container_name: senseRedis
    ports:
      - "6379:6379"  # Expose the Redis port
    volumes:
      - redis-data:/data
    networks:
      - sense-networks

# shared network
networks:
  sense-networks:
    driver: bridge


volumes:
  sense-app:
  redis-data:
  pgdata:
