pattern_dict_regex = {
    "review": r'\b(?:systematic review|Literature Review|review|Meta-Analysis|Critical Review|Peer Review|Book Review|Editorial Review|Review Article)\b',
    "number_of_studies": r'\b(?:\d+ studies|\d+ study)\b',
    "population_specificGroup": r'\b(?:mother|mother of|father|father of|elderly|Older adults/elderly|men|woman|child|children|adolescent|adult|young|kids|newborn|baby|babies|Young Adults)\b',
    "population_OtherSpecificGroup": r'\b(?:travelers|caregivers|caregiver|parents|parents/caregivers|healthcare|healthcare workers|pregnant|pregnant women)\b',
    "population_ageGroup": r'\b(?:\d{1}-\d{1} years|\d{1}-\d{1} years|\d{2}-\d{2} years?|between \d{1}-\d{1} years|between \d{1}-\d{2} years|between \d{2}-\d{2} years?)\b',
    "population_immuneStatus": r'\b(?:immunocompromised|healthy)\b',
    "intervention_vaccinePredictableDisease": r'\b(?:COVID-19|COVID 19|COVID19|COVID|influenza|Dengue|rotavirus)\b',
    "intervention_vaccineOptions": r'\b(?:live|non-live|adjuvants|adjuvant|non-adjuvants|non-adjuvant)\b',
    "topic_acceptance": r'\b(?:Barriers|Barrier|vaccine barriers|knowledge|vaccination willingness and intentions|HPV vaccine acceptability, acceptability|Awareness and knowledge|Awareness|facilitators of and barriers|awareness, knowledge, acceptability, and intention|knowledge and acceptability|sociodemographics, knowledge, attitudes or other factors|knowledge and awareness|attitudes and beliefs|Knowledge and Attitude|attitude|knowledge, awareness, and attitude)\b',
    "topic_coverage": r'\b(?:Vaccine uptake|decreased vaccine initiation and completion|initiated vaccination but did not complete the vaccine series|Uptake|the uptake|actual uptake)\b',
    "topic_economic": r'\b(?:Cost Effectiveness|cost-effectiveness|cost|cost effectiveness|economic evaluation|Cost-effectiveness of HPV vaccination strategies)\b',
    "topic_ethicalIssues": r'\b(?:racial|ethnic|ethnic minorit(?:y)?|racial minorit(?:y)?|racial/ethnic|racial/ethnic minorit(?:y)?|racial disparit(?:y)?|ethnic disparit(?:y)?)\b',
    "topic_administration": r'\b(?:Comparison of different human papillomavirus \(HPV\) vaccine types and dose|schedules|different dose schedules|Two doses of HPV vaccine compared with three doses of HPV vaccine|Two doses of HPV vaccine with longer interval compared with two doses of HPV vaccine with shorter interval|Nonavalent HPV vaccine compared with quadrivalent HPV vaccine)\b',
    "topic_efficacyEffectiveness": r'\b(?:Efficacy|doses?|Three doses HPV vaccine compared with control|efficacy of a HPV catch-up vaccination|the effect|Effect of HPV vaccines on outcomes|HPV vaccination efficacy|vaccination efficacy|The Efficacy and Duration of Vaccine Protection|duration of protection following HPV vaccination|efficacy of vaccination|vaccine protection|Impact and Effectiveness|impact or effectiveness of 4vHPV vaccination|effectiveness|impact or effectiveness)\b',
    "topic_immunogenicity": r'\b(?:Immunogenicity|Antibody responses|Immunological outcomes \(geometric mean titre \(GMT\) and seropositivity)\)\b',
    "topic_safety": r'\b(?:Harm|local adverse events|injection-site adverse events|adverse effects|safety|serious adverse events|vaccination safety|serious adverse events|adverse events|serious adverse event|protective effect|safety of HPV vaccine|Ads|onset of autoimmune conditions related to HPV vaccine|events)\b',
    "outcome_infection": r'\b(?:incident infections|persistent infections|infection|HPV related diseases)\b',
    "outcome_hospitalization": r'\b(?:hospitalization)\b',
    "outcome_death": r'\b(?:mortality|overall mortality|cancer related mortality|on overall and cancer mortality)\b',
    "outcome_ICU": r'\b(?:ICU|Intensive care unit)\b',
    "openAccess": r'\b(?:open access)\b',
}
