"""empty message

Revision ID: 78be9e514b65
Revises: 9d26c63c6ded
Create Date: 2023-12-07 13:34:08.076137

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '78be9e514b65'
down_revision = '9d26c63c6ded'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('membrane_proteins')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('membrane_proteins',
    sa.Column('Unnamed: 0', sa.BIGINT(), autoincrement=False, nullable=True),
    sa.Column('DBCOllection', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('citation_type', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('citation_lang', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('citation_keywords', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('journal_title', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('journal_abstract', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('journal_source', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('publication_year', sa.BIGINT(), autoincrement=False, nullable=True),
    sa.Column('publication_date_obj', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('domain', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('other_domain', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('authors', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('country', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('region', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('PII', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('journal_URL', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('document_type', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('review_tags', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('review_bag', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('number_of_studies_tags', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('number_of_studies_bag', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('population_specificGroup_tags', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('population_specificGroup_acronyms_', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('population_specificGroup_bag', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('population_ageGroup_tags', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('population_ageGroup_bag', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('population_immuneStatus_tags', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('population_immuneStatus_bag', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('population_OtherSpecificGroup_tags', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('population_OtherSpecificGroup_bag', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('intervention_vaccinePredictableDisease_tags', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('intervention_vaccinePredictableDisease_bag', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('intervention_vaccineOptions_tags', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('intervention_vaccineOptions_bag', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('topic_acceptance_tags', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('topic_acceptance_bag', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('topic_coverage_tags', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('topic_coverage_bag', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('topic_economic_tags', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('topic_economic_bag', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('topic_ethicalIssues_tags', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('topic_ethicalIssues_bag', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('topic_administration_tags', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('topic_administration_bag', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('topic_efficacyEffectiveness_tags', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('topic_efficacyEffectiveness_bag', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('topic_immunogenicity_tags', postgresql.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('topic_immunogenicity_bag', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('topic_safety_tags', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('topic_safety_bag', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('outcome_infection_tags', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('outcome_infection_bag', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('outcome_hospitalization_tags', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('outcome_hospitalization_bag', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('outcome_death_tags', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('outcome_death_bag', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('outcome_ICU_tags', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('outcome_ICU_bag', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('openAccess_tags', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('openAccess_bag', sa.TEXT(), autoincrement=False, nullable=True)
    )
    # ### end Alembic commands ###
