population_acronyms = {
    "parents" : "cg",
    "caregivers" : "cg",
    "parents/caregivers" : "cg",
    "elderly": "adu",
    "Older adults/elderly": "adu",
    "elderly": "adu",
    "pregnant": "adu",
    "pregnant women": "cg",
    "18-70 year": "adu",
    "9-17 year": "chi, ado",
    "21-65 year": "adu",
    "woman":"adu",
    "child": "chi",
    "children": "chi",
    "adolescent": "ado",
    "adult": "adu",
    "young": "chi",
    "kids": "chi",
    "newborn": "ado",
    "baby": "ado",
    "babies": "ado",
    "young": "chi",
    "Young Adults": "adu",
}

